apiVersion:  v1
kind:  ReplicationController
metadata:
  name:  nginx
  labels:
    tier:  backend
spec:
  template:
    metadata:
      labels:
        app:  v1
      name:  nginx
    spec:
      containers:
        - image:  nginx:1.23.4
          name:  nginx
  replicas:  3
