apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-08-06T20:39:08Z"
  generation: 1
  labels:
    run: nginx
    tier: frontend
    type: static-pod

  name: nginx
  namespace: default
  resourceVersion: "134040"
  uid: 7b057845-52fd-48b8-9f6b-17dd3ececac9
spec:
  containers:
  - image: nginx
    name: nginx
  nodeName: cka-cluster3-worker
