apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod-test
  name: my-nginx-pod-test
spec:
  containers:
  - image: nginx
    name: nginx-pod-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
